language: node_js
node_js:
  - 6.9.5
sudo: required
cache:
  directories:
    - node_modules
    - .nvm
env:
  global:
    - NODE_ENV=test
    - TEST_DATABASE_URL=postgres://postgres@localhost:5432/opentrials_api_test
    - ELASTICSEARCH_URL=http://localhost:9200
    - URL=http://localhost:10010

addons:
  postgresql: "9.4"
services:
  - postgresql
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.8.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.8.deb && sudo service elasticsearch restart
before_script:
  - touch .env
  - psql -c 'create database opentrials_api_test;' -U postgres
  - npm run migrate
  # Run seed twice to make sure we're cleaning the DB correctly
  - npm run seed
  - npm run seed
  - npm run reindex
script:
  - npm run e2e
  - npm run coveralls
