swagger: "2.0"
info:
  version: "0.0.1"
  title: OpenTrials API
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /swagger.yaml:
    x-swagger-pipe: swagger_raw
  /search:
    x-swagger-router-controller: search
    get:
      tags:
        - trials
      description: Search trials
      operationId: search
      parameters:
        - name: q
          in: query
          description: The search query
          type: string
        - name: page
          in: query
          description: The page number
          type: integer
          minimum: 1
          default: 1
        - name: per_page
          in: query
          description: Number of items per page
          type: integer
          minimum: 10
          maximum: 100
          default: 20
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SearchResults"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /trials/{id}:
    x-swagger-router-controller: trials
    get:
      tags:
        - trials
      description: Returns list of trials
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: id
          in: path
          description: ID of the trial
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Trial"
        # responses may fall through to errors
        "404":
          description: Trial not found
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Trial:
    required:
      - id
      - public_title
      - brief_summary
      - registration_date
      - locations
      - interventions
      - persons
    properties:
      id:
        type: string
      public_title:
        type: string
      brief_summary:
        type: string
      registration_date:
        type: string
        format: date-time
      locations:
        type: array
        items:
          $ref: '#/definitions/TrialLocation'
      interventions:
        type: array
        items:
          $ref: '#/definitions/TrialIntervention'
      persons:
        type: array
        items:
          $ref: '#/definitions/TrialPerson'

  TrialLocation:
    required:
      - attributes
    properties:
      role:
        type: string
        enum:
          - recruitment_countries
          - other
      attributes:
        $ref: '#/definitions/Location'
  Location:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
        enum:
          - country
          - city
          - other

  TrialIntervention:
    required:
      - attributes
    properties:
      role:
        type: string
        enum:
          - other
      attributes:
        $ref: '#/definitions/Intervention'
  Intervention:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
        enum:
          - drug
          - other

  TrialPerson:
    required:
      - attributes
    properties:
      role:
        type: string
        enum:
          - principal_investigator
          - public_queries
          - scientific_queries
          - other
      attributes:
        $ref: '#/definitions/Person'
  Person:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
        enum:
          - other

  SearchResults:
    required:
      - total_count
      - items
    properties:
      total_count:
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/Trial'

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
